# Generated by Django 3.2.6 on 2022-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShort', '0002_alter_urlmodel_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='ip_address',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
