# Generated by Django 3.2.6 on 2022-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShort', '0003_urlmodel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='location',
            field=models.CharField(default='INDIA', max_length=500),
        ),
    ]
